### ISSUE TITLE
Separate base starter project vs sample starter project

### ISSUE THREAD

**Issue by patrickhammond** [atomicrobot/Carbon-Android#10]
Pull all the github example code into an `example/github` branch and keep `master` pretty clean so that when starting up a new project you don't need to go start off by deleting a bunch of stuff.  As `master` is updated, someone will need to ensure that `example/github` is kept up to date.  Eventually it might make more sense to move that into its own repository and treat this as the upstream repo, but we can grow into that later.

**Comment by atoennis** [comment]
> Eventually it might make more sense to move that into its own repository and treat this as the upstream repo, but we can grow into that later.
I think that's over my head... what do you mean by that? 😄

**Comment by stuartsoft** [comment]
Probably just fork this repo to make a separate "ClientStarterProject", then do a pull from this repo every once in a while to keep it updated.

**Comment by stuartsoft** [comment]
(Might also be cool if we had a .io page to share our starter project and encourage others to use it/ contribute)

**Comment by patrickhammond** [comment]
@atoennis Fork vs branching as a way of managing the base project and sample.  I want to make sure there is little friction to contributing to it but also little friction to being able to validate a change in a real implementation.  Not sure which is best.

@stuartsoft https://github.com/madebyatomicrobot/madebyatomicrobot.github.io drives http://madebyatomicrobot.github.io/ .  You can see by the commit log we could probably start fresh if there are better templates now.

**Comment by bradyjohnk** [comment]
Going to try this method for starter vs reference project

starter-koin (to replace main-koin)
starter-hilt (to replace master)
reference (will be the main branch moving forward, using koin, for all work we don't want included in a starter project and will include a "cookbook")
