### ISSUE TITLE
Investigate TeamCity version control/kotlin config

### ISSUE THREAD

**Issue by patrickhammond** [atomicrobot/Carbon-Android#12]

**Comment by patrickhammond** [comment]
I'd also like to see if there is a way we can set up a required weekly build to ensure projects are staying fresh with the build tools, etc.

@stuartsoft You had put some thought into this before, I think? Would you be able to dig into if the TeamCity Kotlin DSL supports this type of configuration?

**Comment by ascheetz** [comment]
Builds are now occurring in Bitrise and version is being pulled from there
