### ISSUE TITLE
Ensure all installed packages are uninstalled at end of build

### ISSUE THREAD

**Issue by patrickhammond** [atomicrobot/Carbon-Android#13]
Some of our older devices don't have a ton of space and it causes insufficient storage errors for other projects.  Need to make sure that all packages (including test packages) are uninstalled from the device after the build ends.  We should already do this at the beginning of the process too...maybe leverage that existing task?

**Comment by stuartsoft** [comment]
You could add a shell script as the last build task that simply forks a new process (to another shell script) that calls adb to uninstall the app after a short delay. This way the build will done before adb tries to uninstall. I've used this trick in the past when I want Team City to perform an action after a build has completed.

**Comment by patrickhammond** [comment]
I'd like to see this taken care of as part of #12

**Comment by bradyjohnk** [comment]
Not using TeamCity anymore
