### ISSUE TITLE
Thread management updates

### ISSUE THREAD

**Issue by atoennis** [atomicrobot/Carbon-Android#53]
### Two changes:
* Let the interactor manage which thread pool to subscribe to
* Let the view model manage which thread pool to observe on

### Reason:
The view model doesn't have visibility to know what the interactor is doing to know what thread pool to subscribe to.  For example, the interactor could be fetching data from over the network, off disk or in memory, each which may require a different thread pool.

### Pro/Con:
**pro**: threading behaviors are declared where they make the most sense
**con**: you lose some affinity for quickly groking threading behaviors

**Comment by bradyjohnk** [comment]
should be resolved with newer MVI setup and corroutines/flow
