### ISSUE TITLE
Migrate gradle to Kotlin DSL

### ISSUE THREAD

**Issue by atoennis** [atomicrobot/Carbon-Android#75]
Migrate the gradle files to the Kotlin DSL.  See https://blog.gradle.org/gradle-kotlin-dsl-release-candidate

**Comment by weverb2** [comment]
I vote for holding off on this until the DSL is more stable.  Been having lots of issues with it on other projects.

**Comment by atoennis** [comment]
Agreed, @atomicrobotjohn has had similar issues as well.

**Comment by bradyjohnk** [comment]
moved to issue #115 and is being worked currently
